repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: no-commit-to-branch
        args: ['--pattern', '^(?!^(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert|bump)/[-a-zA-Z0-9]+)']

-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    -   id: black
        language_version: python
        args:
            - --line-length=79

-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args:
        - --profile=black
        - --line-width=79


-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake

-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args:
        - --max-line-length=79
        - --ignore=W503, B008

-   repo: https://github.com/pylint-dev/pylint
    rev: v3.0.1
    hooks:
    -   id: pylint
        args:
        -   '*.py'
        -   --disable=import-error
        -   --disable=too-few-public-methods,R0801
        -   --disable=too-many-arguments
        -   --disable=unused-import


-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        additional_dependencies: [tokenize-rt==3.2.0, ]
        args:
        - --strict
        - --ignore-missing-imports
        - --allow-untyped-decorators


-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        exclude: ^app/test/

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
    -   id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ "@commitlint/config-conventional" ]
