repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake8

-   repo: https://github.com/psf/black
    rev: v23.10.1
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.4
    hooks:
    -   id: docformatter

-   repo: https://github.com/PyCQA/flake8
    rev: v6.1.0
    hooks:
    -   id: flake8

-   repo: https://github.com/pylint-dev/pylint
    rev: v23.10.1
    hooks:
    -   id: pylint

-   repo: https://github.com/PyCQA/pydocstyle
    rev: v6.3.0
    hooks:
    -   id: pydocstyle

-   repo: https://github.com/PyCQA/bandit
    rev: v1.7.5
    hooks:
    -   id: bandit

