name: 'Python Lint'
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8

      - name: Run flake8
        run: |
          flake8 --max-line-length=79 --ignore=W503,B008
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          architecture: x64

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pylint

      - name: Run pylint
        run: |
          pylint $(find . -type f -name "*.py") --disable=too-few-public-methods,import-error,too-many-arguments,unused-import,R0801

#  mypy:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Setup Python Environment
#        uses: actions/setup-python@v3
#        with:
#          python-version: '3.10'
#          architecture: x64
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt mypy
#
#      - name: Type checking with mypy
#        run: |
#          mypy $(find . -type f -name "*.py") --strict --ignore-missing-imports --allow-untyped-decorators
